export const ADMIN = "ltemirlan2000@gmail.com";

export const ACTIONS = {
  GET_MESSAGE: "GET_MESSAGE",
  GET_DATA: "GET_DATA",
  GET_COMMENTS: "GET_COMMENTS",
  GET_ONE_PRODUCT: "GET_ONE_PRODUCT",
  GET_ONE_COMMENT: "GET_ONE_COMMENT",
  GET_PRODUCT_CHAPTER: "GET_PRODUCT_CHAPTER",

  GET_CART: "GET_CART",
  CHANGE_CART_LENGTH: "CHANGE_CART_LENGTH",
};
export const JSON_API_PRODUCTS = "http://localhost:8000/products";
